/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log.h"

bool_t
xdr_mensaje (XDR *xdrs, mensaje *objp)
{

	 if (!xdr_string (xdrs, &objp->usuario, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operacion, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->publicacion, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fecha, 256))
		 return FALSE;
	return TRUE;
}
